# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowTwo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(731, 438)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 151, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.widgetFirst = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.widgetFirst.setContentsMargins(0, 0, 0, 0)
        self.widgetFirst.setObjectName("widgetFirst")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 80, 361, 351))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.widgetMain = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.widgetMain.setContentsMargins(0, 0, 0, 0)
        self.widgetMain.setObjectName("widgetMain")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.widgetMain.addWidget(self.label)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(560, 80, 160, 351))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.widgetSecond = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.widgetSecond.setContentsMargins(0, 0, 0, 0)
        self.widgetSecond.setObjectName("widgetSecond")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 711, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCreate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnCreate.setObjectName("btnCreate")
        self.horizontalLayout.addWidget(self.btnCreate)
        self.btnDo = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnDo.setObjectName("btnDo")
        self.horizontalLayout.addWidget(self.btnDo)
        self.btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn.setObjectName("btn")
        self.horizontalLayout.addWidget(self.btn)
        self.btnBd = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnBd.setObjectName("btnBd")
        self.horizontalLayout.addWidget(self.btnBd)
        self.btnSett = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSett.setObjectName("btnSett")
        self.horizontalLayout.addWidget(self.btnSett)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(160, 70, 16, 361))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(540, 80, 16, 361))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Выберите программу."))
        self.btnCreate.setText(_translate("MainWindow", "Создать эксперимент"))
        self.btnDo.setText(_translate("MainWindow", "Провести эксперимент"))
        self.btn.setText(_translate("MainWindow", "?????????????"))
        self.btnBd.setText(_translate("MainWindow", "База данных"))
        self.btnSett.setText(_translate("MainWindow", "Настройки"))
