# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowOne.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowCreate(object):
    def setupUi(self, WindowCreate):
        WindowCreate.setObjectName("WindowCreate")
        WindowCreate.resize(736, 442)
        self.centralwidget = QtWidgets.QWidget(WindowCreate)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 80, 371, 351))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.widgetMain = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.widgetMain.setContentsMargins(0, 0, 0, 0)
        self.widgetMain.setObjectName("widgetMain")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.widgetMain.addWidget(self.label)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(569, 80, 151, 351))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.widgetSecond = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.widgetSecond.setContentsMargins(0, 0, 0, 0)
        self.widgetSecond.setObjectName("widgetSecond")
        self.btnChange = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnChange.setObjectName("btnChange")
        self.widgetSecond.addWidget(self.btnChange)
        self.btnAdd = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnAdd.setObjectName("btnAdd")
        self.widgetSecond.addWidget(self.btnAdd)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 711, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCreate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnCreate.setObjectName("btnCreate")
        self.horizontalLayout.addWidget(self.btnCreate)
        self.btnDo = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnDo.setObjectName("btnDo")
        self.horizontalLayout.addWidget(self.btnDo)
        self.btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn.setObjectName("btn")
        self.horizontalLayout.addWidget(self.btn)
        self.btnBd = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnBd.setObjectName("btnBd")
        self.horizontalLayout.addWidget(self.btnBd)
        self.btnSett = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSett.setObjectName("btnSett")
        self.horizontalLayout.addWidget(self.btnSett)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(160, 80, 20, 351))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(550, 80, 20, 351))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 80, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.btnDel = QtWidgets.QPushButton(self.centralwidget)
        self.btnDel.setGeometry(QtCore.QRect(10, 200, 149, 28))
        self.btnDel.setObjectName("btnDel")
        WindowCreate.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowCreate)
        QtCore.QMetaObject.connectSlotsByName(WindowCreate)

    def retranslateUi(self, WindowCreate):
        _translate = QtCore.QCoreApplication.translate
        WindowCreate.setWindowTitle(_translate("WindowCreate", "MainWindow"))
        self.label.setText(_translate("WindowCreate", "Выберите программу."))
        self.btnChange.setText(_translate("WindowCreate", "Изменить"))
        self.btnAdd.setText(_translate("WindowCreate", "Создать новый"))
        self.btnCreate.setText(_translate("WindowCreate", "Создать эксперимент"))
        self.btnDo.setText(_translate("WindowCreate", "Провести эксперимент"))
        self.btn.setText(_translate("WindowCreate", "?????????????"))
        self.btnBd.setText(_translate("WindowCreate", "База данных"))
        self.btnSett.setText(_translate("WindowCreate", "Настройки"))
        self.btnDel.setText(_translate("WindowCreate", "Удалить"))
